version: '3'
services:
  mongo:
    image: mongo:3.6.1
    volumes:
      - mongo-volume:/data/db
    ports:
      - '27017:27017'
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    entrypoint: bash
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo:27017/kodi
    ports:
      - '3005:3005'
    volumes:
      - .:/home/node/app
      - node-modules:/home/node/app/node_modules
    depends_on:
      - mongo
volumes:
  node-modules:
  mongo-volume:
